

services:
  # Database Migration Job (runs once)
  migrate:
    image: ${DOCKER_REGISTRY:-}${DOCKER_IMAGE_NAME:-solar-api}:${DOCKER_TAG:-latest}
    container_name: ${COMPOSE_PROJECT_NAME:-solar}_migrate${ENVIRONMENT_SUFFIX:-}
    environment:
      DATABASE_URL: mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@103.70.13.116:3306/${MYSQL_DATABASE}
    # No dependency on local MySQL since we're using external database
    networks:
      - solar_network
    command: ["npm", "run", "db:migrate"]
    restart: "no"

  # NestJS Application
  app:
    # Use pre-built image from registry
    image: ${DOCKER_REGISTRY:-}${DOCKER_IMAGE_NAME:-solar-api}:${DOCKER_TAG:-latest}
    container_name: ${COMPOSE_PROJECT_NAME:-solar}_app${ENVIRONMENT_SUFFIX:-}
    restart: ${RESTART_POLICY:-unless-stopped}
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      DATABASE_URL: mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@${VPS_HOST}:3306/${MYSQL_DATABASE}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN:-15m}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      JWT_REFRESH_EXPIRES_IN: ${JWT_REFRESH_EXPIRES_IN:-7d}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      VPS_HOST: ${VPS_HOST}
      PORT: 3000
    ports:
      - '${APP_PORT:-3000}:3000'
    depends_on:
      migrate:
        condition: service_completed_successfully
    networks:
      - solar_network
    volumes:
      - app_uploads:/app/uploads
    healthcheck:
      test: ['CMD', 'node', '-e', 'require("http").get("http://localhost:3000/health", (res) => process.exit(res.statusCode === 200 ? 0 : 1)).on("error", () => process.exit(1))']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    logging:
      driver: 'json-file'
      options:
        max-size: '${LOG_MAX_SIZE:-10m}'
        max-file: '${LOG_MAX_FILE:-3}'

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: ${COMPOSE_PROJECT_NAME:-solar}_nginx${ENVIRONMENT_SUFFIX:-}
    restart: ${RESTART_POLICY:-unless-stopped}
    ports:
      - '${HTTP_PORT:-80}:80'
      - '${HTTPS_PORT:-443}:443'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - nginx_logs:/var/log/nginx
    depends_on:
      - app
    networks:
      - solar_network
    logging:
      driver: 'json-file'
      options:
        max-size: '${LOG_MAX_SIZE:-10m}'
        max-file: '${LOG_MAX_FILE:-3}'

volumes:
  app_uploads:
    driver: local
  nginx_logs:
    driver: local

networks:
  solar_network:
    driver: bridge
